"""Explicit required canonical features per opportunity. No silent column guessing."""
from __future__ import annotations

from typing import Any, Dict, List, Optional

# Each required entry: feature name in context, equipment_id, canonical_point (mapper name).
_Req = Dict[str, str]


def _r(name: str, equipment_id: str, canonical_point: Optional[str] = None) -> _Req:
    return {"name": name, "equipment_id": equipment_id, "canonical_point": canonical_point or name}


CATALOG: Dict[str, Dict[str, Any]] = {
    "O1": {
        "title": "Optimum Start/Stop",
        "equipment_id": "ZONE-01",
        "required": [
            _r("zone_temperature", "ZONE-01"),
            _r("outdoor_air_temperature", "SITE"),
            _r("occupancy", "ZONE-01"),
            _r("enable", "AHU-01"),
            _r("cooling_setpoint", "ZONE-01"),
        ],
        "current_feature": "enable",
        "recommended_point": "enable",
        "recommended_equipment": "AHU-01",
        "unit": None,
        "control": True,
        "kind": "CONTROL",
    },
    "O2": {
        "title": "Space Temperature Bands",
        "equipment_id": "ZONE-01",
        "required": [
            _r("zone_temperature", "ZONE-01"),
            _r("cooling_setpoint", "ZONE-01"),
            _r("heating_setpoint", "ZONE-01"),
            _r("occupancy", "ZONE-01"),
            _r("outdoor_air_temperature", "SITE"),
        ],
        "current_feature": "cooling_setpoint",
        "recommended_point": "cooling_setpoint",
        "recommended_equipment": "ZONE-01",
        "unit": "°C",
        "control": True,
        "kind": "CONTROL",
    },
    "O3": {
        "title": "Master AHU SAT",
        "equipment_id": "AHU-01",
        "required": [
            _r("supply_air_temperature", "AHU-01"),
            _r("sat_setpoint", "AHU-01"),
            _r("outdoor_air_temperature", "SITE"),
            _r("return_air_temperature", "AHU-01"),
            _r("fan_speed", "AHU-01"),
            _r("zone_temperature", "ZONE-01"),
        ],
        "current_feature": "supply_air_temperature",
        "recommended_point": "sat_setpoint",
        "recommended_equipment": "AHU-01",
        "unit": "°C",
        "control": True,
        "kind": "CONTROL",
    },
    "O4": {
        "title": "Chiller Staging",
        "equipment_id": "CH-01",
        "required": [
            _r("status", "CH-01"),
            _r("cooling_load", "CH-01", "load"),
            _r("chw_supply_temperature", "CH-01"),
            _r("chw_return_temperature", "CH-01"),
            _r("chw_supply_setpoint", "CH-01"),
            _r("enable", "CH-01"),
        ],
        "current_feature": "enable",
        "recommended_point": "enable",
        "recommended_equipment": "CH-01",
        "unit": None,
        "control": True,
        "kind": "CONTROL",
    },
    "O5": {
        "title": "Duct Static Pressure",
        "equipment_id": "AHU-01",
        "required": [
            _r("duct_static_pressure", "AHU-01"),
            _r("static_setpoint", "AHU-01"),
            _r("fan_speed", "AHU-01"),
        ],
        "current_feature": "duct_static_pressure",
        "recommended_point": "static_setpoint",
        "recommended_equipment": "AHU-01",
        "unit": "in.w.c.",
        "control": True,
        "kind": "CONTROL",
    },
    "O6": {
        "title": "HHW Reset",
        "equipment_id": "HHW-01",
        "required": [
            _r("hhw_supply_temperature", "HHW-01"),
            _r("hhw_return_temperature", "HHW-01"),
            _r("outdoor_air_temperature", "SITE"),
            _r("heating_demand", "HHW-01"),
            _r("hhw_setpoint", "HHW-01"),
        ],
        "current_feature": "hhw_supply_temperature",
        "recommended_point": "hhw_setpoint",
        "recommended_equipment": "HHW-01",
        "unit": "°C",
        "control": True,
        "kind": "CONTROL",
    },
    "O7": {
        "title": "CHW Reset",
        "equipment_id": "CH-01",
        "required": [
            _r("chw_supply_temperature", "CH-01"),
            _r("chw_return_temperature", "CH-01"),
            _r("outdoor_air_temperature", "SITE"),
            _r("cooling_load", "CH-01", "load"),
            _r("chw_supply_setpoint", "CH-01"),
        ],
        "current_feature": "chw_supply_temperature",
        "recommended_point": "chw_supply_setpoint",
        "recommended_equipment": "CH-01",
        "unit": "°C",
        "control": True,
        "kind": "CONTROL",
    },
    "O8": {
        "title": "Cooling Water Reset",
        "equipment_id": "CW-01",
        "required": [
            _r("cw_supply_temperature", "CW-01"),
            _r("cw_return_temperature", "CW-01"),
            _r("outdoor_air_temperature", "SITE"),
            _r("status", "CH-01"),
            _r("cw_setpoint", "CW-01"),
        ],
        "current_feature": "cw_supply_temperature",
        "recommended_point": "cw_setpoint",
        "recommended_equipment": "CW-01",
        "unit": "°C",
        "control": True,
        "kind": "CONTROL",
    },
    "O9": {
        "title": "Electronic Expansion Valve",
        "equipment_id": "CH-01",
        "required": [
            _r("suction_temperature", "CH-01"),
            _r("discharge_pressure", "CH-01"),
            _r("cooling_load", "CH-01", "load"),
            _r("status", "CH-01"),
        ],
        "current_feature": "suction_temperature",
        "recommended_point": "status",
        "recommended_equipment": "CH-01",
        "unit": "°C",
        "control": False,
        "kind": "REVIEW",
    },
    "O10": {
        "title": "Economy Cycle",
        "equipment_id": "AHU-01",
        "required": [
            _r("outdoor_air_temperature", "SITE"),
            _r("return_air_temperature", "AHU-01"),
            _r("oa_damper", "AHU-01"),
            _r("enable", "AHU-01"),
        ],
        "current_feature": "oa_damper",
        "recommended_point": "oa_damper",
        "recommended_equipment": "AHU-01",
        "unit": "%",
        "control": True,
        "kind": "CONTROL",
        "ml": False,
    },
    "O11": {
        "title": "Night Purge",
        "equipment_id": "AHU-01",
        "required": [
            _r("outdoor_air_temperature", "SITE"),
            _r("zone_temperature", "ZONE-01"),
            _r("occupancy", "ZONE-01"),
            _r("enable", "AHU-01"),
            _r("oa_damper", "AHU-01"),
        ],
        "current_feature": "oa_damper",
        "recommended_point": "oa_damper",
        "recommended_equipment": "AHU-01",
        "unit": "%",
        "control": True,
        "kind": "CONTROL",
    },
    "O12": {
        "title": "Demand Ventilation / CO2",
        "equipment_id": "AHU-01",
        "required": [
            _r("co2", "AHU-01"),
            _r("occupancy", "ZONE-01"),
            _r("oa_damper", "AHU-01"),
            _r("zone_temperature", "ZONE-01"),
        ],
        "current_feature": "oa_damper",
        "recommended_point": "oa_damper",
        "recommended_equipment": "AHU-01",
        "unit": "%",
        "control": True,
        "kind": "CONTROL",
    },
    "O13": {
        "title": "DCV CO",
        "equipment_id": "AHU-01",
        "required": [
            _r("co_ppm", "ZONE-01"),
            _r("occupancy", "ZONE-01"),
            _r("oa_damper", "AHU-01"),
        ],
        "current_feature": "oa_damper",
        "recommended_point": "oa_damper",
        "recommended_equipment": "AHU-01",
        "unit": "%",
        "control": True,
        "kind": "CONTROL",
        "notes": "Do not substitute CO2 for CO.",
    },
    "O14": {
        "title": "CHW Pump",
        "equipment_id": "P-01",
        "required": [
            _r("speed", "P-01"),
            _r("flow", "P-01"),
            _r("differential_pressure", "P-01"),
            _r("chw_supply_temperature", "CH-01"),
            _r("chw_return_temperature", "CH-01"),
            _r("status", "P-01"),
        ],
        "current_feature": "differential_pressure",
        "recommended_point": "speed",
        "recommended_equipment": "P-01",
        "unit": "%",
        "control": True,
        "kind": "CONTROL",
    },
    "O15": {
        "title": "Air-Cooled Head Pressure",
        "equipment_id": "CH-01",
        "required": [
            _r("head_pressure", "CH-01"),
            _r("outdoor_air_temperature", "SITE"),
            _r("fan_speed", "AHU-01"),
            _r("status", "CH-01"),
            _r("cooling_load", "CH-01", "load"),
        ],
        "current_feature": "head_pressure",
        "recommended_point": "head_pressure",
        "recommended_equipment": "CH-01",
        "unit": "kPa",
        "control": True,
        "kind": "CONTROL",
    },
    "O16": {
        "title": "Water-Cooled Head Pressure",
        "equipment_id": "CH-01",
        "required": [
            _r("condenser_water_temperature", "CH-01"),
            _r("cw_supply_temperature", "CW-01"),
            _r("flow", "P-01"),
            _r("cooling_load", "CH-01", "load"),
            _r("status", "CH-01"),
        ],
        "current_feature": "condenser_water_temperature",
        "recommended_point": "condenser_water_temperature",
        "recommended_equipment": "CH-01",
        "unit": "°C",
        "control": True,
        "kind": "CONTROL",
    },
    "O17": {
        "title": "Energy Management Planning",
        "equipment_id": "CH-01",
        "required": [
            _r("energy", "CH-01"),
            _r("cooling_load", "CH-01", "load"),
            _r("runtime", "CH-01"),
        ],
        "current_feature": "energy",
        "recommended_point": None,
        "recommended_equipment": None,
        "unit": "kWh",
        "control": False,
        "kind": "ADVISORY",
    },
    "O18": {
        "title": "Training Awareness",
        "equipment_id": "SITE",
        "required": [
            _r("occupancy", "ZONE-01"),
        ],
        "current_feature": "occupancy",
        "recommended_point": None,
        "recommended_equipment": None,
        "unit": None,
        "control": False,
        "kind": "ADVISORY",
    },
    "O19": {
        "title": "Equipment Maintenance",
        "equipment_id": "CH-01",
        "required": [
            _r("status", "CH-01"),
            _r("alarms", "CH-01"),
            _r("runtime", "CH-01"),
        ],
        "current_feature": "status",
        "recommended_point": None,
        "recommended_equipment": None,
        "unit": None,
        "control": False,
        "kind": "MAINTENANCE",
    },
    "O20": {
        "title": "Control Software",
        "equipment_id": "SITE",
        "required": [
            _r("status", "CH-01"),
        ],
        "current_feature": "status",
        "recommended_point": None,
        "recommended_equipment": None,
        "unit": None,
        "control": False,
        "kind": "REVIEW",
    },
}


# What the opportunity agent uses to decide (not only the sklearn registry row).
ENGINE_BY_OID: Dict[str, str] = {
    "O1": "Random Forest",
    "O2": "Random Forest",
    "O3": "Random Forest",
    "O4": "Random Forest",
    "O5": "Random Forest",
    "O6": "Random Forest",
    "O7": "Random Forest",
    "O8": "Random Forest",
    "O9": "Random Forest",
    "O10": "Enthalpy rules",
    "O11": "Random Forest",
    "O12": "Random Forest",
    "O13": "CO thresholds",
    "O14": "Random Forest",
    "O15": "Random Forest",
    "O16": "Random Forest",
    "O17": "Random Forest",
    "O18": "Training records",
    "O19": "Random Forest",
    "O20": "Controls review",
}


def catalog_for(opportunity_id: str) -> Dict[str, Any]:
    oid = (opportunity_id or "").strip().upper()
    if oid not in CATALOG:
        raise KeyError(oid)
    row = dict(CATALOG[oid])
    row["engine"] = ENGINE_BY_OID.get(oid) or row.get("engine") or "—"
    return row


def all_opportunity_ids() -> List[str]:
    return list(CATALOG.keys())
